AutoQuant::AutoH2oGLMRegression(
  OutputSelection = c("EvalMetrics", "Score_TrainData"),
  data = NULL,
  TrainOnFull = FALSE,
  ValidationData = NULL,
  TestData = NULL,
  TargetColumnName = NULL,
  FeatureColNames = NULL,
  RandomColNumbers = NULL,
  InteractionColNumbers = NULL,
  WeightsColumn = NULL,
  MaxMem = {gc();paste0(as.character(floor(as.numeric(system("awk '/MemFree/ {print $2}' /proc/meminfo", intern=TRUE)) / 1000000)),"G")},
  NThreads = max(1, parallel::detectCores()-2),
  ModelID = "FirstModel",
  ReturnModelObjects = TRUE,
  model_path = NULL,
  metadata_path = NULL,
  SaveModelObjects = FALSE,
  SaveInfoToPDF = FALSE,
  IfSaveModel = "mojo",
  H2OShutdown = TRUE,
  H2OStartUp = TRUE,
  DebugMode = FALSE,
  TransformNumericColumns = NULL,
  Methods = c("BoxCox", "Asinh", "Log", "LogPlus1", "Sqrt", "Asin", "Logit"),
  NumOfParDepPlots = 3,
  GridTune = FALSE,
  GridStrategy = "Cartesian",
  StoppingRounds = 10,
  MaxRunTimeSecs = 3600 * 24 * 7,
  MaxModelsInGrid = 2,
  Distribution = "gaussian",
  Link = "identity",
  TweedieLinkPower = NULL,
  TweedieVariancePower = NULL,
  eval_metric = "RMSE",
  RandomDistribution = NULL,
  RandomLink = NULL,
  Solver = "AUTO",
  Alpha = 0.5,
  Lambda = NULL,
  LambdaSearch = FALSE,
  NLambdas = -1,
  Standardize = TRUE,
  RemoveCollinearColumns = FALSE,
  InterceptInclude = TRUE,
  NonNegativeCoefficients = FALSE)


devtools::load_all(path = "C:/Users/Bizon/Documents/GitHub/AutoQuant/R")
library(Rodeo)

OutputSelection = c("EvalMetrics", "Score_TrainData")
data = data.table::fread("C:/Users/Bizon/Documents/GitHub/rappwd/Fake_Beverage_Data.csv")
ValidationData = NULL
TestData = NULL
TargetColumnName = "ClassTarget"
FeatureColNames = c("Brand","Category","Beverage Flavor","Daily Liters","Daily Units")
TrainOnFull = FALSE
RandomColNumbers = which(names(data) %in% "Customer")
RandomDistribution = "Gaussian"
RandomLink = "Identity"
InteractionColNumbers = NULL
WeightsColumn = NULL
MaxMem = "32G"
NThreads = max(1, parallel::detectCores()-2)
ModelID = "FirstModel"
ReturnModelObjects = TRUE
model_path = NULL
metadata_path = NULL
SaveModelObjects = FALSE
SaveInfoToPDF = FALSE
IfSaveModel = "mojo"
H2OShutdown = TRUE
H2OStartUp = TRUE
DebugMode = FALSE
TransformNumericColumns = NULL
Methods = c("BoxCox", "Asinh", "Log", "LogPlus1", "Sqrt", "Asin", "Logit")
NumOfParDepPlots = 3
GridTune = FALSE
GridStrategy = "Cartesian"
StoppingRounds = 10
MaxRunTimeSecs = 3600 * 24 * 7
MaxModelsInGrid = 2
Distribution = "binomial"
Link = "logit"
eval_metric = "auc"
Solver = "AUTO"
Alpha = 0.5
Lambda = NULL
LambdaSearch = FALSE
NLambdas = -1
Standardize = TRUE
RemoveCollinearColumns = FALSE
InterceptInclude = TRUE
NonNegativeCoefficients = FALSE
CostMatrixWeights = c(0,1,1,0)

TargetType.="classifier"
TargetColumnName.=TargetColumnName
data.=data
ValidationData.=ValidationData
TestData.=TestData
TrainOnFull.=TrainOnFull
FeatureColNames.=FeatureColNames
SaveModelObjects.=SaveModelObjects
model_path.=model_path
ModelID.=ModelID



