install.packages("devtools")
install.packages("data.table")
install.packages("collapse")
install.packages("bit64")
install.packages("doParallel")
install.packages("foreach")
install.packages("lubridate")
install.packages("timeDate")
install.packages("combinat")
install.packages("DBI")
install.packages("e1071")
install.packages("fBasics")
install.packages("itertools")
install.packages("MLmetrics")
install.packages("nortest")
install.packages("pROC")
install.packages("RColorBrewer")
install.packages("RPostgres")
install.packages("Rfast")
install.packages("scatterplot3d")
install.packages("stringr")
install.packages("xgboost")
install.packages("lightgbm")
install.packages("regmedint")
install.packages("RCurl")
install.packages("jsonlite")
install.packages("h2o")
devtools::install_github("https://github.com/catboost/catboost/releases/download/v1.1.1/catboost-R-Windows-1.1.1tgz", INSTALL_opts = c("--no-multiarch", "--no-test-load"))
install.packages("echarts4r")
devtools::install_github("AdrianAntico/AutoNLP", upgrade = FALSE, dependencies = FALSE, force = TRUE)
devtools::install_github("AdrianAntico/AutoPlots", upgrade = FALSE, dependencies = FALSE, force = TRUE)
devtools::install_github("AdrianAntico/Rodeo", upgrade = FALSE, dependencies = FALSE, force = TRUE)
devtools::install_github("AdrianAntico/AutoQuant", upgrade = FALSE, dependencies = FALSE, force = TRUE)
install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinydashboardPlus")
install.packages("AzureStor")
install.packages("shinyWidgets")
install.packages("gitlink")
devtools::install_github("AdrianAntico/esquisse", upgrade = FALSE, dependencies = FALSE, force = TRUE)
install.packages("arrow")
install.packages("shiny.fluent")
install.packages("shinyjqui")
install.packages("shinyAce")
install.packages("prompter")
install.packages("gyro")
install.packages("arrangements")
devtools::install_github("AdrianAntico/Rappture", upgrade = FALSE, dependencies = FALSE, force = TRUE, auth_token = "ghp_eHRZjqviiYfD4r0uTdSQs9913qD7kG2VNO6e")

# install.packages("tsoutliers")
# install.packages("recommenderlab")
# install.packages("ggplot2")
# install.packages("gridExtra")
# install.packages("forecast")
# install.packages("fpp")
# install.packages("lme4")
# install.packages("StanHeaders")
# install.packages("rstan")
# install.packages("brms")
# install.packages("DT")
# install.packages("plotly")
# devtools::install_github("AdrianAntico/prettydoc", upgrade = FALSE, dependencies = FALSE, force = TRUE)
