# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----
# ML Reports                                                      ----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----

#' @title Run_ModelInsightsReport
#'
#' @description Run_ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by DataMuse supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL
#' @param SampleSize Default 100000
#' @param ModelObject Output from a DataMuse supervised learning function
#' @param ModelID ModelID used in the DataMuse supervised learning function
#' @param SourcePath Path to directory with DataQuant Model Output
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                    FeatureColumnNames = NULL,
                                    SampleSize = 100000,
                                    ModelObject = NULL,
                                    ModelID = NULL,
                                    SourcePath = NULL,
                                    OutputPath = NULL) {

  # Directory reference
  appDir <- system.file("r-markdowns", package = "DataMuse")

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Globalize the parameters
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # ModelObject
  ModelObject <<- ModelObject

  # Finalize Passthrough
  if(!is.null(ModelObject)) {

    # DataSets
    ModelObject[['TestData']] <- ModelObject[['TestData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    if(TrainDataInclude) {
      ModelObject[['TrainData']] <- ModelObject[['TrainData']][order(runif(.N))][seq_len(min(.N, SampleSize))]
    } else {
      ModelObject[['TrainData']] <- NULL
    }

    # Meta info
    TargetType <- ModelObject[["ArgsList"]][["TargetType"]]
    if(TargetType == "Binary Classification") TargetType <- "classification"
    TargetColumnName <- ModelObject[['ArgsList']][['TargetColumnName']]
    PredictionColumnName <- ModelObject[["ArgsList"]][["PredictionColumnName"]]
    TargetLevels <- ModelObject[["ArgsList"]][["TargetLevels"]]
    Algo <- tolower(ModelObject[["ArgsList"]][["Algo"]])
    if(is.null(FeatureColumnNames)) {
      FeatureColumnNames <- ModelObject[['ColNames']][[1L]]
    }
    ArgsList <- ModelObject[['ArgsList']]

  } else {
    return(NULL)
  }

  if(length(ModelObject[['TestData']]) == 0L && length(ModelObject[['TrainData']]) == 0L) return(NULL)

  # Metadata args
  TargetType <- TargetType
  TargetLevels <- TargetLevels
  ModelID <- ModelID
  Algo <- Algo
  SourcePath <- SourcePath
  OutputPath <- OutputPath
  OutputPathName <- file.path(OutputPath, paste0('MLReport-', ModelID, '-', TargetType, '.html'))

  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  # Select Rmarkdown Report and Run it ----
  # @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

  # Regression Markdown
  if(tolower(TargetType) == 'regression') {
    rmarkdown::render(
      input = file.path(appDir, 'Regression_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # Classification Markdown
  if(tolower(TargetType) == 'classification') {
    rmarkdown::render(
      input = file.path(appDir, 'Classification_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }

  # MultiClass Markdown
  if(tolower(TargetType) == 'multiclass') {
    rmarkdown::render(
      input = file.path(appDir, 'MultiClass_ModelInsights.Rmd'),
      output_file = OutputPathName)
  }
}

#' @title ModelInsightsReport
#'
#' @description ModelInsightsReport is an Rmarkdown report for viewing the model insights generated by DataMuse supervised learning functions
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param TrainDataInclude Default FALSE. If FALSE, no derived visuals or metrics for TrainData
#' @param FeatureColumnNames NULL. Feature column names as character vector.
#' @param SampleSize Default 100000
#' @param ModelObject Returned output from regression, classificaiton, and multiclass Remix Auto_() models. Currenly supports CatBoost, XGBoost, and LightGBM models
#' @param ModelID ModelID used in the DataMuse supervised learning function
#' @param SourcePath Path to directory with DataMuse Model Output
#' @param OutputPath Path to directory where the html will be saved
#' @param GlobalVars ls() don't use
#' @param KeepOutput NULL A list of output names to select. Pass in as a character vector. E.g. c('Test_VariableImportance', 'Train_VariableImportance')
#'
#' @export
ModelInsightsReport <- function(TrainDataInclude = FALSE,
                                FeatureColumnNames = NULL,
                                SampleSize = 100000,
                                ModelObject = NULL,
                                ModelID = 'ModelTest',
                                SourcePath = NULL,
                                OutputPath = NULL,
                                KeepOutput = NULL,
                                GlobalVars = ls()) {

  # Run Function
  Run_ModelInsightsReport(
    TrainDataInclude = TrainDataInclude,
    FeatureColumnNames = FeatureColumnNames,
    SampleSize = SampleSize,
    ModelObject = ModelObject,
    ModelID = ModelID,
    SourcePath = SourcePath,
    OutputPath = OutputPath)

  # Remove objects
  GlobalVarsNew <- ls()
  rm(list = c(setdiff(GlobalVarsNew, c(GlobalVars, KeepOutput))))
}

# ----

# ----

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----
# EDA Reports                                                     ----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----

#' @title Run_EDA_Report
#'
#' @description Run_EDA_Report is an Rmarkdown report for EDA
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param data NULL
#' @param DataName NULL
#' @param UnivariateVars NULL
#' @param CorrVars NULL
#' @param TrendVars NULL
#' @param TrendDateVar NULL
#' @param TrendGroupVar NULL
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_EDA_Report <- function(data = NULL,
                           DataName = NULL,
                           UnivariateVars = NULL,
                           CorrVars = NULL,
                           TrendVars = NULL,
                           TrendDateVar = NULL,
                           TrendGroupVar = NULL,
                           OutputPath = NULL) {

  appDir <- system.file("r-markdowns", package = "DataMuse")
  print(head(data))
  print(UnivariateVars)
  print(CorrVars)
  print(TrendVars)
  print(TrendDateVar)
  print(TrendGroupVar)


  data <- data
  UnivariateVars <- UnivariateVars
  CorrVars <- CorrVars
  TrendVars <- TrendVars
  TrendDateVar <- TrendDateVar
  TrendGroupVar <- TrendGroupVar
  OutputPathName <- file.path(OutputPath, paste0('EDAReport-', DataName, '.html'))
  rmarkdown::render(
    input = file.path(appDir, 'EDA.Rmd'),
    output_file = OutputPathName)
}

#' @title EDAReport
#'
#' @description EDAReport is an Rmarkdown report for viewing EDA results
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param data NULL
#' @param DataName NULL
#' @param UnivariateVars NULL
#' @param CorrVars NULL
#' @param TrendVars NULL
#' @param TrendDateVar NULL
#' @param TrendGroupVar NULL
#' @param OutputPath List of output objects
#'
#' @export
EDAReport <- function(data = NULL,
                      DataName = NULL,
                      UnivariateVars = NULL,
                      CorrVars = NULL,
                      TrendVars = NULL,
                      TrendDateVar = NULL,
                      TrendGroupVar = NULL,
                      OutputPath = NULL) {

  Run_EDA_Report(
    data = data,
    DataName = DataName,
    UnivariateVars = UnivariateVars,
    CorrVars = CorrVars,
    TrendVars = TrendVars,
    TrendDateVar = TrendDateVar,
    TrendGroupVar = TrendGroupVar,
    OutputPath = OutputPath)
}

# ----

# ----

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----
# Plotting Reports                                                ----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----

#' @title Run_Plotting_Report
#'
#' @description Run_Plotting_Report is an Rmarkdown report for Plot Output
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param PlotOutputList NULL
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_Plotting_Report <- function(PlotOutputList = NULL,
                                OutputPath = NULL) {

  appDir <- system.file("r-markdowns", package = "DataMuse")
  PlotOutputList <- PlotOutputList
  OutputPathName <- file.path(OutputPath, paste0('Plotting-', gsub(pattern = ":", "_", Sys.time()), '.html'))
  rmarkdown::render(
    input = file.path(appDir, 'Plotting.Rmd'),
    output_file = OutputPathName)
}

#' @title PlottingReport
#'
#' @description PlottingReport is an Rmarkdown report for viewing Plotting results
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param PlotOutputList NULL
#' @param OutputPath List of output objects
#'
#' @export
PlottingReport <- function(PlotOutputList = NULL,
                           OutputPath = NULL) {

  Run_Plotting_Report(
    PlotOutputList = PlotOutputList,
    OutputPath = OutputPath)
}

# ----

# ----

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----
# Tables Reports                                                  ----
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ----

#' @title Run_Tables_Report
#'
#' @description Run_Tables_Report is an Rmarkdown report for Table Output
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param DataOuts NULL
#' @param DataOutputList NULL
#' @param OutputPath Path to directory where the html will be saved
#'
#' @noRd
Run_Tables_Report <- function(DataOuts = NULL,
                              DataList = NULL,
                              OutputPath = NULL) {

  appDir <- system.file("r-markdowns", package = "DataMuse")
  DataList <- DataList
  DataOuts <- DataOuts
  OutputPathName <- file.path(OutputPath, paste0('Tables-', gsub(pattern = ":", "_", Sys.time()), '.html'))
  rmarkdown::render(
    input = file.path(appDir, 'Tables.Rmd'),
    output_file = OutputPathName)
}

#' @title TablesReport
#'
#' @description TablesReport is an Rmarkdown report for viewing Tables results
#'
#' @author Adrian Antico
#' @family Reports
#'
#' @param DataOuts NULL
#' @param DataList NULL
#' @param OutputPath List of output objects
#'
#' @export
TablesReport <- function(DataOuts = NULL,
                         DataList = NULL,
                         OutputPath = NULL) {

  Run_Tables_Report(
    DataOuts = DataOuts,
    DataList = DataList,
    OutputPath = OutputPath)
}

# ----

# ----
